name: ci-laureline

on:
    push:
      branches: ["master"]
    pull_request:
      branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code source
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installation de Node.js via le fichier .nvmrc
      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm' # Active le cache automatique des dépendances

      # 3. Installation propre des dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Vérification du style de code (Lint)
      - name: Run Lint
        run: npm run lint

      # 5. Exécution des tests unitaires
      - name: Run Tests
        run: npm test